apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: YWRtaW4=
  mongo-password: MWYyZDFlMmU2N2Rm
  # You can include additional key value pairs as you do with Opaque Secrets